$schema = "./node_modules/wrangler/config-schema.json"

name = "poko-website-builder"
compatibility_date = "2025-03-10"
pages_build_output_dir = "./dist"

[vars]
BUN_VERSION = "1.3.7"
UNSTABLE_PRE_BUILD = "bun i"
SKIP_DEPENDENCY_INSTALL = "true"
