siteName: Repères ASBL
productionUrl: https://www.reperes.be/
logo: /_images/reperes-asbl-logo-sans-bords-rvb-01.webp
languages:
  - code: fr
    name: Français
    customUrlPrefix:
      prefix: ''
    status: published
    isCmsDefault: false
    isWebsiteDefault: true
